In [1]:
import keras

Using TensorFlow backend.


In [0]:
from keras.utils import to_categorical

In [0]:
dataset=['Pizza','Burger','Bread','Bread','Bread','Burger','Pizza','Burger']

In [0]:
import pandas as pd
import numpy as np
from numpy import array
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [0]:
myarray=array(dataset)

In [0]:
label_encoder=LabelEncoder()
integer_encoded=label_encoder.fit_transform(myarray)

In [8]:
print(integer_encoded)

[2 1 0 0 0 1 2 1]


In [9]:
kerasencoded=to_categorical(integer_encoded)
print(kerasencoded)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [0]:
#Handling missing values in keras
dataset=pd.read_csv("pima-indians-diabetes.data.csv",header=None)

In [12]:
print(dataset.head(15))

     0    1   2   3    4     5      6   7  8
0    6  148  72  35    0  33.6  0.627  50  1
1    1   85  66  29    0  26.6  0.351  31  0
2    8  183  64   0    0  23.3  0.672  32  1
3    1   89  66  23   94  28.1  0.167  21  0
4    0  137  40  35  168  43.1  2.288  33  1
5    5  116  74   0    0  25.6  0.201  30  0
6    3   78  50  32   88  31.0  0.248  26  1
7   10  115   0   0    0  35.3  0.134  29  0
8    2  197  70  45  543  30.5  0.158  53  1
9    8  125  96   0    0   0.0  0.232  54  1
10   4  110  92   0    0  37.6  0.191  30  0
11  10  168  74   0    0  38.0  0.537  34  1
12  10  139  80   0    0  27.1  1.441  57  0
13   1  189  60  23  846  30.1  0.398  59  1
14   5  166  72  19  175  25.8  0.587  51  1


In [13]:
print(dataset[[1,2,3,4,5]].head())

     1   2   3    4     5
0  148  72  35    0  33.6
1   85  66  29    0  26.6
2  183  64   0    0  23.3
3   89  66  23   94  28.1
4  137  40  35  168  43.1


In [14]:
print(dataset[[1,2,3,4,5]]==0)

         1      2      3      4      5
0    False  False  False   True  False
1    False  False  False   True  False
2    False  False   True   True  False
3    False  False  False  False  False
4    False  False  False  False  False
5    False  False   True   True  False
6    False  False  False  False  False
7    False   True   True   True  False
8    False  False  False  False  False
9    False  False   True   True   True
10   False  False   True   True  False
11   False  False   True   True  False
12   False  False   True   True  False
13   False  False  False  False  False
14   False  False  False  False  False
15   False   True   True   True  False
16   False  False  False  False  False
17   False  False   True   True  False
18   False  False  False  False  False
19   False  False  False  False  False
20   False  False  False  False  False
21   False  False   True   True  False
22   False  False   True   True  False
23   False  False  False   True  False
24   False  False  False 

In [15]:
print((dataset[[1,2,3,4,5]]==0).sum())

1      5
2     35
3    227
4    374
5     11
dtype: int64


In [0]:
dataset[[1,2,3,4,5]]=dataset[[1,2,3,4,5]].replace(0,np.NAN)

In [17]:
print(dataset.head(15))

     0      1     2     3      4     5      6   7  8
0    6  148.0  72.0  35.0    NaN  33.6  0.627  50  1
1    1   85.0  66.0  29.0    NaN  26.6  0.351  31  0
2    8  183.0  64.0   NaN    NaN  23.3  0.672  32  1
3    1   89.0  66.0  23.0   94.0  28.1  0.167  21  0
4    0  137.0  40.0  35.0  168.0  43.1  2.288  33  1
5    5  116.0  74.0   NaN    NaN  25.6  0.201  30  0
6    3   78.0  50.0  32.0   88.0  31.0  0.248  26  1
7   10  115.0   NaN   NaN    NaN  35.3  0.134  29  0
8    2  197.0  70.0  45.0  543.0  30.5  0.158  53  1
9    8  125.0  96.0   NaN    NaN   NaN  0.232  54  1
10   4  110.0  92.0   NaN    NaN  37.6  0.191  30  0
11  10  168.0  74.0   NaN    NaN  38.0  0.537  34  1
12  10  139.0  80.0   NaN    NaN  27.1  1.441  57  0
13   1  189.0  60.0  23.0  846.0  30.1  0.398  59  1
14   5  166.0  72.0  19.0  175.0  25.8  0.587  51  1


In [0]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
values=dataset.values

In [0]:
from sklearn.model_selection import KFold
x=values[:,0:8]
y=values[:,8]

In [20]:
model=LinearDiscriminantAnalysis()
kfold=KFold(n_splits=3,random_state=7)
result=cross_val_score(model,x,y,cv=kfold,scoring='accuracy')
print(result.mean())

ValueError: ignored

In [21]:
#Impute msng vals
dataset[[1,2,3,4,5]]=dataset[[1,2,3,4,5]].replace(0,np.NaN)
dataset.dropna(inplace=True)
print(dataset.head(15)) #ntc row index

     0      1     2     3      4     5      6   7  8
3    1   89.0  66.0  23.0   94.0  28.1  0.167  21  0
4    0  137.0  40.0  35.0  168.0  43.1  2.288  33  1
6    3   78.0  50.0  32.0   88.0  31.0  0.248  26  1
8    2  197.0  70.0  45.0  543.0  30.5  0.158  53  1
13   1  189.0  60.0  23.0  846.0  30.1  0.398  59  1
14   5  166.0  72.0  19.0  175.0  25.8  0.587  51  1
16   0  118.0  84.0  47.0  230.0  45.8  0.551  31  1
18   1  103.0  30.0  38.0   83.0  43.3  0.183  33  0
19   1  115.0  70.0  30.0   96.0  34.6  0.529  32  1
20   3  126.0  88.0  41.0  235.0  39.3  0.704  27  0
24  11  143.0  94.0  33.0  146.0  36.6  0.254  51  1
25  10  125.0  70.0  26.0  115.0  31.1  0.205  41  1
27   1   97.0  66.0  15.0  140.0  23.2  0.487  22  0
28  13  145.0  82.0  19.0  110.0  22.2  0.245  57  0
31   3  158.0  76.0  36.0  245.0  31.6  0.851  28  1


In [0]:
values=dataset.values
x=values[:,0:8]
y=values[:,8]

In [23]:
import numpy as np
model=LinearDiscriminantAnalysis()
kfold=KFold(n_splits=3,random_state=7)
result=cross_val_score(model,x,y,cv=kfold,scoring='accuracy')
print(result.mean())

0.7858289293403797


In [24]:
#Nxt technique we are mean imputing 
dataset[[1,2,3,4,5]]=dataset[[1,2,3,4,5]].replace(0,np.NaN)
dataset.fillna(dataset.mean(),inplace=True)
print(dataset.head(15))

     0      1     2     3      4     5      6   7  8
3    1   89.0  66.0  23.0   94.0  28.1  0.167  21  0
4    0  137.0  40.0  35.0  168.0  43.1  2.288  33  1
6    3   78.0  50.0  32.0   88.0  31.0  0.248  26  1
8    2  197.0  70.0  45.0  543.0  30.5  0.158  53  1
13   1  189.0  60.0  23.0  846.0  30.1  0.398  59  1
14   5  166.0  72.0  19.0  175.0  25.8  0.587  51  1
16   0  118.0  84.0  47.0  230.0  45.8  0.551  31  1
18   1  103.0  30.0  38.0   83.0  43.3  0.183  33  0
19   1  115.0  70.0  30.0   96.0  34.6  0.529  32  1
20   3  126.0  88.0  41.0  235.0  39.3  0.704  27  0
24  11  143.0  94.0  33.0  146.0  36.6  0.254  51  1
25  10  125.0  70.0  26.0  115.0  31.1  0.205  41  1
27   1   97.0  66.0  15.0  140.0  23.2  0.487  22  0
28  13  145.0  82.0  19.0  110.0  22.2  0.245  57  0
31   3  158.0  76.0  36.0  245.0  31.6  0.851  28  1


In [26]:
values=dataset.values
x=values[:,0:8]
y=values[:,8]
model=LinearDiscriminantAnalysis()
kfold=KFold(n_splits=3,random_state=7)
result=cross_val_score(model,x,y,cv=kfold,scoring='accuracy')
print(result.mean())

0.7858289293403797


In [0]:
from sklearn.preprocessing import Imputer
dataset[[1,2,3,4,5]]=dataset[[1,2,3,4,5]].replace(0,np.NaN)
values=dataset.values

In [28]:
print(values)

[[  1.     89.     66.    ...   0.167  21.      0.   ]
 [  0.    137.     40.    ...   2.288  33.      1.   ]
 [  3.     78.     50.    ...   0.248  26.      1.   ]
 ...
 [  2.     88.     58.    ...   0.766  22.      0.   ]
 [ 10.    101.     76.    ...   0.171  63.      0.   ]
 [  5.    121.     72.    ...   0.245  30.      0.   ]]


In [0]:
imputer=Imputer()
values=imputer.fit_transform(values) #by default imputer means

In [30]:
x=values[:,0:8]
y=values[:,8]
model=LinearDiscriminantAnalysis()
kfold=KFold(n_splits=3,random_state=7)
result=cross_val_score(model,x,y,cv=kfold,scoring='accuracy')
print(result.mean())

0.7858289293403797


In [34]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
result=cross_val_score(model,x,y,cv=kfold,scoring='accuracy')
print(result.mean())

0.7679976512037582


In [0]:
from xgboost.sklearn import XGBClassifier
model=XGBClassifier()

In [36]:
result=cross_val_score(model,x,y,cv=kfold,scoring='accuracy')
print(result.mean())

0.7679976512037582
